name: resource_id
description: A Dart package for creating, parsing, and validating robust and immutable resource identifiers.
version: 0.1.0
repository: https://github.com/dropbear-software/resource_id
issue_tracker: https://github.com/dropbear-software/resource_id/issues

environment:
  sdk: ^3.9.3

# Add regular dependencies here.
dependencies:
  base32_codec: ^1.0.0
  meta: ^1.17.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
